### ISSUE TITLE
Error message on invalid name doesn't specify file

### ISSUE THREAD

**Issue by sethladd** [xxgreg/mustache#9]
Hi,

Just got this error:

```
Tag contained invalid characters in name, allowed: 0-9, a-z, A-Z, underscore, and minus, at: 45:13.
```

But which file? :)

Full stack trace:

```
Tag contained invalid characters in name, allowed: 0-9, a-z, A-Z, underscore, and minus, at: 45:13.
#0      _checkTagChars (package:mustache/template.dart:53:4)
#1      _parseTokens (package:mustache/template.dart:19:18)
#2      _parse (package:mustache/template.dart:10:24)
#3      parse (package:mustache/mustache.dart:17:48)
#4      NewHtmlGenerator.generatePackage (package:dartdoc/src/new_html_generator.dart:58:24)
#5      NewHtmlGenerator.generate (package:dartdoc/src/new_html_generator.dart:35:20)
#6      DartDoc.generateDocs.<anonymous closure> (package:dartdoc/dartdoc.dart:76:58)
#7      List.forEach (dart:core-patch/growable_array.dart:254)
#8      DartDoc.generateDocs (package:dartdoc/dartdoc.dart:76:24)
#9      main (file:///Users/sethladd/Code/dartdoc/bin/dartdoc.dart:45:19)
#10     _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#11     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)
```

**Comment by xxgreg** [comment]
In 0.2 you can pass a name to the Template constructor. This name is shown in the error messages.

**Comment by sethladd** [comment]
Nice!
